# Generated by Django 2.2 on 2020-05-10 21:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='car_brand',
            new_name='brand',
        ),
        migrations.RemoveField(
            model_name='item',
            name='car_model',
        ),
        migrations.AddField(
            model_name='item',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
